INSERT INTO teams(id, nombre) VALUES(1, 'Alavés'),
(2, 'Almería'),
(3, 'Athletic de Bilbao'),
(4, 'Atlético de Madrid'),
(5, 'Barcelona'),
(6, 'Betis'),
(7, 'Cádiz'),
(8, 'Celta'),
(9, 'Getafe'),
(10, 'Girona'),(11, 'Granada'),
(12, 'Las Palmas'),
(13, 'Mallorca'),
(14, 'Osasuna'),
(15, 'Real Sociedad'),
(16, 'Rayo Vallecano'),
(17, 'Real Madrid'),
(18, 'Sevilla'),
(19, 'Valencia'),
(20, 'Villarreal');

INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(1, 'España, 1921, Alfonso Fernández de Trocóniz, Luis García Plaza, www.deportivoalaves.com, Mendizorroza, 19200, Plaza Amadeo García de Salazar, s/n, Álava, Vitoria'),
(2, 'España, 1989, Turki Al-Sheikh, Vicente Moreno, www.udalmeria.com, Power Horse Stadium, 15200, Complejo Deportivo de la Vega de Acá, s/n, Almería, Álmería'),
(3, 'España, 1898, Jon Uriarte, Ernesto Valverde, www.athletic-club.net, San Mamés, 53332, C/ Ventosa Bidea,36, Bilbao, Vizcaya'),
(4, 'España, 1903, Enrique Cerezo, Diego Pablo Simeone, www.clubatleticodemadrid.com, Civitas Metropolitano, 68000, Desconocida'),
(5, 'España, 1899, Joan Laporta, Xavi Hernández, www.fcbarcelona.com, Spotify Camp Nou, 99264, Carrer d´Árístides Maillol, Barcelona, Barcelona'),
(6, 'España, 1907, Ángel Haro, Manuel Pellegrini, www.realbetisbalompie.es, Benito Villamarín, 60721, Avda. Heliópolis, s/n, Sevilla'),
(7, 'España, 1910, Manuel Vizcaíno Fernández, Sergio González, www.cadizcf.com, Nuevo Mirandilla, 19500, Plaza de Madrid, 21, Cádiz, Cádiz'),
(8, 'España, 1923, Carlos Mouriño, Rafa Benítez, www.celtavigo.net, Abanca-Balaídos, 31800, Avda, de Balaídos, s/n, Vigo, Pontevedra'),
(9, 'España, 1983, Ángel Torres, José Bordalás, www.getafecf.com, Coliseum Alfonso Pérez, 17393, Avda/ Teresa de Calcuta, 4, Getafe, Madrid'),
(10, 'España, 1930, Delfi Geli, Míchel Sánchez, www.gironafc.cat, Montilivi, 10000, Avda/ Montilivi, 141, Girona, Girona'),
(11, 'España, 1931, Jiang Lizhang, Paco López, www.granadacf.es, Nuevo Los Cármenes, 23156, C/ del Pintor Manuel Maldonado, Granada, Granada'),
(12, 'España, 1949, Miguel Ángel Ramírez Alonso, Xavi García Pimienta, www.udlaspalmas.es, Gran Canaria, 32500, C/ Fondos de Segura, s/n, Las Palmas de Gran Canaria, Las Palmas'),
(13, 'España, 1916, Andy Kohlberg, Javier Aguirre, www.rcdmallorca.es, Estadi Mallorca Son Moix, 23142, Cami Reis s/n, Palma de Mallorca, Baleares'),
(14, 'España, 1920, Luis Sabalza, Jagoba Arrasate, www.osasuna.es, El Sadar, 23516, C/ Sadar, s/n, Pamplona, Navarra'),
(15, 'España, 1909, Jokin Aperribay, Imanol Alguacil, www.realsociedad.com, Reale Arena, 32076, Paseo de Anoeta,1 San Sebastián, Guipúzcoa'),
(16, 'España, 1924, Raúl Martín Presa, Francisco Rodríguez, www.rayovallecano.es, Estadio de Vallecas, 14708, C/ Payaso Fofó, 1, Madrid, Madrid'),
(17, 'España, 1902, Florentino Pérez, Carlo Ancelotti, www.realmadrid.com, Santiago Bernabéu, 85454, Avda/ Concha Espina, 1, Madrid, Madrid'),
(18, 'España, 1890, José Castro, José Luis Mendilibar, www.sevillafc.es, Ramón Sánchez-Pizjuán, 45500, Avda/ Eduardo Dato, s/n, Sevilla, Sevilla'),
(19, 'España, 1919, Layhoon Chan, Rubén Baraja, www.valenciacf.es, Mestalla, 52600, Avda/ Suecia, s/n, Valencia, Valencia'),
(20, 'España, 1942, Fernando Roig, Quique Setien, www.villarrealcf.es, Estadio de la Cerámica, 22000, Calle de Benicàssim, Villarreal, Castellón');

INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES