INSERT INTO team(id, nombre) VALUES(1, 'Alavés')
INSERT INTO team(id, nombre) VALUES(2, 'Almería')
INSERT INTO team(id, nombre) VALUES(3, 'Athletic de Bilbao')
INSERT INTO team(id, nombre) VALUES(4, 'Atlético de Madrid')
INSERT INTO team(id, nombre) VALUES(5, 'Barcelona')
INSERT INTO team(id, nombre) VALUES(6, 'Betis')
INSERT INTO team(id, nombre) VALUES(7, 'Cádiz')
INSERT INTO team(id, nombre) VALUES(8, 'Celta')
INSERT INTO team(id, nombre) VALUES(9, 'Getafe')
INSERT INTO team(id, nombre) VALUES(10, 'Girona')
INSERT INTO team(id, nombre) VALUES(11, 'Granada')
INSERT INTO team(id, nombre) VALUES(12, 'Las Palmas')
INSERT INTO team(id, nombre) VALUES(13, 'Mallorca')
INSERT INTO team(id, nombre) VALUES(14, 'Osasuna')
INSERT INTO team(id, nombre) VALUES(15, 'Real Sociedad')
INSERT INTO team(id, nombre) VALUES(16, 'Rayo Vallecano')
INSERT INTO team(id, nombre) VALUES(17, 'Real Madrid')
INSERT INTO team(id, nombre) VALUES(18, 'Sevilla')
INSERT INTO team(id, nombre) VALUES(19, 'Valencia')
INSERT INTO team(id, nombre) VALUES(20, 'Villarreal')

INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(1, 'España, 1921, Alfonso Fernández de Trocóniz, Luis García Plaza, www.deportivoalaves.com, Mendizorroza, 19200, Plaza Amadeo García de Salazar, s/n, Álava, Vitoria')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(2, 'España, 1989, Turki Al-Sheikh, Vicente Moreno, www.udalmeria.com, Power Horse Stadium, 15200, Complejo Deportivo de la Vega de Acá, s/n, Almería, Álmería')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(3, 'España, 1898, Jon Uriarte, Ernesto Valverde, www.athletic-club.net, San Mamés, 53332, C/ Ventosa Bidea,36, Bilbao, Vizcaya')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(4, 'España, 1903, Enrique Cerezo, Diego Pablo Simeone, www.clubatleticodemadrid.com, Civitas Metropolitano, 68000, Desconocida')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(5, 'España, 1899, Joan Laporta, Xavi Hernández, www.fcbarcelona.com, Spotify Camp Nou, 99264, Carrer d´Árístides Maillol, Barcelona, Barcelona')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(6, 'España, 1907, Ángel Haro, Manuel Pellegrini, www.realbetisbalompie.es, Benito Villamarín, 60721, Avda. Heliópolis, s/n, Sevilla')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(7, 'España, 1910, Manuel Vizcaíno Fernández, Sergio González, www.cadizcf.com, Nuevo Mirandilla, 19500, Plaza de Madrid, 21, Cádiz, Cádiz')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(8, 'España, 1923, Carlos Mouriño, Rafa Benítez, www.celtavigo.net, Abanca-Balaídos, 31800, Avda, de Balaídos, s/n, Vigo, Pontevedra')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(9, 'España, 1983, Ángel Torres, José Bordalás, www.getafecf.com, Coliseum Alfonso Pérez, 17393, Avda/ Teresa de Calcuta, 4, Getafe, Madrid')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(10, 'España, 1930, Delfi Geli, Míchel Sánchez, www.gironafc.cat, Montilivi, 10000, Avda/ Montilivi, 141, Girona, Girona')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(11, 'España, 1931, Jiang Lizhang, Paco López, www.granadacf.es, Nuevo Los Cármenes, 23156, C/ del Pintor Manuel Maldonado, Granada, Granada')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(12, 'España, 1949, Miguel Ángel Ramírez Alonso, Xavi García Pimienta, www.udlaspalmas.es, Gran Canaria, 32500, C/ Fondos de Segura, s/n, Las Palmas de Gran Canaria, Las Palmas')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(13, 'España, 1916, Andy Kohlberg, Javier Aguirre, www.rcdmallorca.es, Estadi Mallorca Son Moix, 23142, Cami Reis s/n, Palma de Mallorca, Baleares')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(14, 'España, 1920, Luis Sabalza, Jagoba Arrasate, www.osasuna.es, El Sadar, 23516, C/ Sadar, s/n, Pamplona, Navarra')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(15, 'España, 1909, Jokin Aperribay, Imanol Alguacil, www.realsociedad.com, Reale Arena, 32076, Paseo de Anoeta,1 San Sebastián, Guipúzcoa')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(16, 'España, 1924, Raúl Martín Presa, Francisco Rodríguez, www.rayovallecano.es, Estadio de Vallecas, 14708, C/ Payaso Fofó, 1, Madrid, Madrid')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(17, 'España, 1902, Florentino Pérez, Carlo Ancelotti, www.realmadrid.com, Santiago Bernabéu, 85454, Avda/ Concha Espina, 1, Madrid, Madrid')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(18, 'España, 1890, José Castro, José Luis Mendilibar, www.sevillafc.es, Ramón Sánchez-Pizjuán, 45500, Avda/ Eduardo Dato, s/n, Sevilla, Sevilla')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(19, 'España, 1919, Layhoon Chan, Rubén Baraja, www.valenciacf.es, Mestalla, 52600, Avda/ Suecia, s/n, Valencia, Valencia')
INSERT INTO details(id, país, fundación, presidente, entrenador, web, sede, aforo, dirección) VALUES(20, 'España, 1942, Fernando Roig, Quique Setien, www.villarrealcf.es, Estadio de la Cerámica, 22000, Calle de Benicàssim, Villarreal, Castellón')
